Front\FrontBundle\Entity\RequestedCoursesVotes:
  type: entity
  table: requested_courses_votes
  repositoryClass: Front\FrontBundle\Repository\RequestedCoursesVotesRepository
  fields:
    id:
      id: true
      type: integer
      unsigned: false
      nullable: false
      generator:
        strategy: IDENTITY
    date:
      type: datetime
      nullable: false
    ip:
      type: string
      length: 45
      fixed: false
      nullable: false
    isActivated:
      type: integer
      unsigned: false
      nullable: false
      column: is_activated
    isDeleted:
      type: integer
      unsigned: false
      nullable: false
      column: is_deleted
  oneToOne:
    requestedCourses:
      targetEntity: RequestedCourses
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        requested_courses_id:
          referencedColumnName: id
      orphanRemoval: false
  oneToOne:
    students:
      targetEntity: Students
      cascade: {  }
      mappedBy: null
      inversedBy: null
      joinColumns:
        students_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
